version: '3.8'

services:
  flask-app:
    env_file:
      - .env
    image: flask-wallet-app:latest
    container_name: walletcontainer
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:22001:22001"
    volumes:
      - app-logs:/var/log/wallet


    restart: unless-stopped



volumes:
  app-logs: